CREATE database Minions;
USE Minions;
CREATE TABLE minions(
	id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    CONSTRAINT pk_id
    PRIMARY KEY(id)
);
CREATE TABLE towns (
    town_id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_town_id PRIMARY KEY (town_id)
);
ALTER TABLE towns
DROP COLUMN town_id;
ALTER TABLE towns
ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT NOT NULL;
ALTER TABLE minions
ADD COLUMN town_id INT,
ADD CONSTRAINT fk_town_id FOREIGN KEY (town_id) REFERENCES towns(id);