ALTER TABLE towns
DROP COLUMN town_id;
ALTER TABLE towns
ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT NOT NULL;
ALTER TABLE minions
ADD COLUMN town_id INT,
ADD CONSTRAINT fk_town_id FOREIGN KEY (town_id) REFERENCES towns(id);